  server:
    port: 8081
  spring:
    cloud:
      config:
        server:
          git:
            default-label: main
            uri: https://github.com/silvina-riera/MonoRepo-ApiFlights.git
            search-paths: config-data
  application:
    name: config-server